---
# tasks file for docker
- name: Install dependencies
  ansible.builtin.apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - ca-certificates
    - curl

- name: directory keyrings proper setup
  ansible.builtin.command: sudo install -m 0755 -d /etc/apt/keyrings

- name: copy key for apt
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: set proper rights for docker.asc
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: configure docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

#- name: configure docker repo
#  ansible.builtin.lineinfile:
#    path: /etc/apt/sources.list.d/docker.list
#    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#    create: yes
#    insertafter: EOF

- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: install docker
  ansible.builtin.apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
